org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8

mod_version=1.0.0-beta
root_package=com.mmce.networks
mod_id=mmcenetworks
mod_name=Modular Machinery: Community Edition Networks
mod_description=Standalone MMCE controller networking for shared public data.
mod_authors=WuXiaoYa
mod_credits=Art by WI_8614_ice
mod_url=https://github.com/wu-xiao-ya/MMCE-Networks
mod_update_json=
mod_logo_path=

mapping_channel=stable
mapping_version=39
use_dependency_at_files=false

minecraft_username=Developer
extra_jvm_args=
extra_tweak_classes=

use_access_transformer=false
access_transformer_locations=mmcenetworks_at.cfg
